
#include "compiler/tokenizer.h"
#include "build/generated/grammar.h"

#define MAKE_TOKEN(name, flags) \
const TokenType TOKEN_##name = { #name, flags, name }

const TokenType TOKEN_EOF = { "EOF", 0, 0 };
const TokenType TOKEN_UNKNOWN = { "UNKNOWN", 0, 0 };

// const TokenType TOKEN_PUNCTUATION = { "PUNCTUATION", 0, 0 };
// const TokenType TOKEN_OPERATOR = { "OPERATOR", 0, 0 }; // FIXME remove

const TokenType TOKEN_SEMICOLON = { "SEMICOLON", 0, ';' };
const TokenType TOKEN_LCURLY = { "LCURLY", 0, '{' };
const TokenType TOKEN_RCURLY = { "RCURLY", 0, '}' };
const TokenType TOKEN_COMMA = { "COMMA", 0, ',' };
const TokenType TOKEN_DOT = { "DOT", 0, '.' };
const TokenType TOKEN_LSQUARE = { "LSQUARE", 0, '[' };
const TokenType TOKEN_RSQUARE = { "RSQUARE", 0, ']' };
const TokenType TOKEN_LPAREN = { "LPAREN", 0, '(' };
const TokenType TOKEN_RPAREN = { "RPAREN", 0, ')' };
const TokenType TOKEN_COLON = { "COLON", 0, ':' };
const TokenType TOKEN_QUESTION = { "QUESTION", 0, '?' };

MAKE_TOKEN(IDENTIFIER, 0);
MAKE_TOKEN(NUMBER, 0);
MAKE_TOKEN(CHARCONST, 0);
MAKE_TOKEN(STRINGCONST, 0);

MAKE_TOKEN(ALIAS, 0);
MAKE_TOKEN(ALLIGNMENT, 0);
MAKE_TOKEN(AS, 0);
MAKE_TOKEN(ARRAY, 0);
MAKE_TOKEN(AUTO, 0);
MAKE_TOKEN(BITFIELD, 0);
MAKE_TOKEN(BREAK, 0);
MAKE_TOKEN(CASE, 0);
MAKE_TOKEN(CONSTANT, 0);
MAKE_TOKEN(CONTINUE, 0);
MAKE_TOKEN(DEFAULT, 0);
MAKE_TOKEN(DO, 0);
MAKE_TOKEN(ELSE, 0);
MAKE_TOKEN(ENUM, 0);
MAKE_TOKEN(FOR, 0);
MAKE_TOKEN(GOTO, 0);
MAKE_TOKEN(IF, 0);
MAKE_TOKEN(IMPORT, 0);
MAKE_TOKEN(INLINE, 0);
MAKE_TOKEN(LINKAGE, 0);
MAKE_TOKEN(LINKNAME, 0);
MAKE_TOKEN(POINTER, 0);
MAKE_TOKEN(PRIVATE, 0);
MAKE_TOKEN(READONLY, 0);
MAKE_TOKEN(REGISTER, 0);
MAKE_TOKEN(RESTRICT, 0);
MAKE_TOKEN(RETURN, 0);
MAKE_TOKEN(SIZEOF, 0);
MAKE_TOKEN(STATIC, 0);
MAKE_TOKEN(STRUCT, 0);
MAKE_TOKEN(SWITCH, 0);
MAKE_TOKEN(TYPEDEF, 0);
MAKE_TOKEN(UNION, 0);
MAKE_TOKEN(USING, 0);
MAKE_TOKEN(VOLATILE, 0);
MAKE_TOKEN(WHILE, 0);

MAKE_TOKEN(ASSIGN_OP, 0);
MAKE_TOKEN(ASSIGN_MULT_OP, 0);
MAKE_TOKEN(ASSIGN_DIV_OP, 0);
MAKE_TOKEN(ASSIGN_MOD_OP, 0);
MAKE_TOKEN(ASSIGN_ADD_OP, 0);
MAKE_TOKEN(ASSIGN_SUB_OP, 0);
MAKE_TOKEN(ASSIGN_SHR_OP, 0);
MAKE_TOKEN(ASSIGN_SHL_OP, 0);
MAKE_TOKEN(ASSIGN_AND_OP, 0);
MAKE_TOKEN(ASSIGN_OR_OP, 0);
MAKE_TOKEN(ASSIGN_XOR_OP, 0);
MAKE_TOKEN(LOG_OR_OP, 0);
MAKE_TOKEN(LOG_AND_OP, 0);
MAKE_TOKEN(OR_OP, 0);
MAKE_TOKEN(AND_ADDR_OP, 0);
MAKE_TOKEN(XOR_OP, 0);
MAKE_TOKEN(EQUAL_OP, 0);
MAKE_TOKEN(NEQUAL_OP, 0);
MAKE_TOKEN(LESS_OP, 0);
MAKE_TOKEN(GREATER_OP, 0);
MAKE_TOKEN(LESSEQ_OP, 0);
MAKE_TOKEN(GREATEREQ_OP, 0);
MAKE_TOKEN(SHL_OP, 0);
MAKE_TOKEN(SHR_OP, 0);
MAKE_TOKEN(ADD_OP, 0);
MAKE_TOKEN(SUB_OP, 0);
MAKE_TOKEN(DIV_OP, 0);
MAKE_TOKEN(MOD_OP, 0);
MAKE_TOKEN(MULT_PTR_OP, 0);
MAKE_TOKEN(NOT_OP, 0);
MAKE_TOKEN(BITNOT_OP, 0);
MAKE_TOKEN(INC_OP, 0);
MAKE_TOKEN(DEC_OP, 0);
MAKE_TOKEN(ELIPSIS, 0);

