
#include "compiler/tokenizer.h"
#include "build/generated/grammar.h"

#define MAKE_TOKEN(name, flags) \
const TokenType TOKEN_##name = { #name, flags, name }

const TokenType TOKEN_EOF = { "EOF", 0, 0 };
const TokenType TOKEN_UNKNOWN = { "UNKNOWN", 0, 0 };

const TokenType TOKEN_SEMICOLON = { "SEMICOLON", 5, ';' };
const TokenType TOKEN_LCURLY = { "LCURLY", 5, '{' };
const TokenType TOKEN_RCURLY = { "RCURLY", 5, '}' };
const TokenType TOKEN_COMMA = { "COMMA", 5, ',' };
const TokenType TOKEN_DOT = { "DOT", 5, '.' };
const TokenType TOKEN_LSQUARE = { "LSQUARE", 5, '[' };
const TokenType TOKEN_RSQUARE = { "RSQUARE", 5, ']' };
const TokenType TOKEN_LPAREN = { "LPAREN", 5, '(' };
const TokenType TOKEN_RPAREN = { "RPAREN", 5, ')' };
const TokenType TOKEN_COLON = { "COLON", 5, ':' };
const TokenType TOKEN_QUESTION = { "QUESTION", 5, '?' };

MAKE_TOKEN(IDENTIFIER, 1);
MAKE_TOKEN(NUMBER, 2);
MAKE_TOKEN(CHARCONST, 3);
MAKE_TOKEN(STRINGCONST, 4);

MAKE_TOKEN(ALIAS, 6);
MAKE_TOKEN(ALLIGNMENT, 6);
MAKE_TOKEN(AS, 6);
MAKE_TOKEN(ARRAY, 6);
MAKE_TOKEN(AUTO, 6);
MAKE_TOKEN(BITFIELD, 6);
MAKE_TOKEN(BREAK, 6);
MAKE_TOKEN(CASE, 6);
MAKE_TOKEN(CONSTANT, 6);
MAKE_TOKEN(CONTINUE, 6);
MAKE_TOKEN(DEFAULT, 6);
MAKE_TOKEN(DO, 6);
MAKE_TOKEN(ELSE, 6);
MAKE_TOKEN(ENUM, 6);
MAKE_TOKEN(FOR, 6);
MAKE_TOKEN(GOTO, 6);
MAKE_TOKEN(IF, 6);
MAKE_TOKEN(IMPORT, 6);
MAKE_TOKEN(INLINE, 6);
MAKE_TOKEN(LINKAGE, 6);
MAKE_TOKEN(LINKNAME, 6);
MAKE_TOKEN(POINTER, 6);
MAKE_TOKEN(PRIVATE, 6);
MAKE_TOKEN(READONLY, 6);
MAKE_TOKEN(REGISTER, 6);
MAKE_TOKEN(RESTRICT, 6);
MAKE_TOKEN(RETURN, 6);
MAKE_TOKEN(SIZEOF, 6);
MAKE_TOKEN(STATIC, 6);
MAKE_TOKEN(STRUCT, 6);
MAKE_TOKEN(SWITCH, 6);
MAKE_TOKEN(TYPEDEF, 6);
MAKE_TOKEN(UNION, 6);
MAKE_TOKEN(USING, 6);
MAKE_TOKEN(VOLATILE, 6);
MAKE_TOKEN(WHILE, 6);

MAKE_TOKEN(ASSIGN_OP, 7);
MAKE_TOKEN(ASSIGN_MULT_OP, 7);
MAKE_TOKEN(ASSIGN_DIV_OP, 7);
MAKE_TOKEN(ASSIGN_MOD_OP, 7);
MAKE_TOKEN(ASSIGN_ADD_OP, 7);
MAKE_TOKEN(ASSIGN_SUB_OP, 7);
MAKE_TOKEN(ASSIGN_SHR_OP, 7);
MAKE_TOKEN(ASSIGN_SHL_OP, 7);
MAKE_TOKEN(ASSIGN_AND_OP, 7);
MAKE_TOKEN(ASSIGN_OR_OP, 7);
MAKE_TOKEN(ASSIGN_XOR_OP, 7);
MAKE_TOKEN(LOG_OR_OP, 7);
MAKE_TOKEN(LOG_AND_OP, 7);
MAKE_TOKEN(OR_OP, 7);
MAKE_TOKEN(AND_ADDR_OP, 7);
MAKE_TOKEN(XOR_OP, 7);
MAKE_TOKEN(EQUAL_OP, 7);
MAKE_TOKEN(NEQUAL_OP, 7);
MAKE_TOKEN(LESS_OP, 7);
MAKE_TOKEN(GREATER_OP, 7);
MAKE_TOKEN(LESSEQ_OP, 7);
MAKE_TOKEN(GREATEREQ_OP, 7);
MAKE_TOKEN(SHL_OP, 7);
MAKE_TOKEN(SHR_OP, 7);
MAKE_TOKEN(ADD_OP, 7);
MAKE_TOKEN(SUB_OP, 7);
MAKE_TOKEN(DIV_OP, 7);
MAKE_TOKEN(MOD_OP, 7);
MAKE_TOKEN(MULT_PTR_OP, 7);
MAKE_TOKEN(NOT_OP, 7);
MAKE_TOKEN(BITNOT_OP, 7);
MAKE_TOKEN(INC_OP, 7);
MAKE_TOKEN(DEC_OP, 7);
MAKE_TOKEN(ELLIPSIS, 5);

